sonar.sources=apps/web/src
sonar.tests=apps/web/src
sonar.test.inclusions=apps/web/src/**/*.test.js,apps/web/src/**/*.spec.js,apps/web/src/**/__tests__/**,apps/web/src/test/**

sonar.exclusions=apps/web/src/**/*.test.js,apps/web/src/**/*.spec.js,apps/web/coverage/**,apps/web/dist/**,apps/web/node_modules/**

sonar.coverage.exclusions=\
apps/web/src/main.jsx,\
apps/web/src/App.jsx,\
apps/web/src/index.css,\
apps/web/src/Routes/**,\
apps/web/src/components/**,\
apps/web/src/pages/**,\
apps/web/src/layouts/**,\
apps/web/src/contexts/**,\
apps/web/src/services/**,\
apps/web/src/hooks/**,\
apps/web/src/**/*.test.js,\
apps/web/src/**/__tests__/**,\
apps/web/src/test/**,\
apps/web/src/patterns/factory/**,\
apps/web/src/patterns/singleton/**,\
apps/web/src/patterns/strategy/**

sonar.cpd.exclusions=\
apps/web/src/components/**,\
apps/web/src/pages/**,\
apps/web/src/layouts/**,\
apps/web/src/contexts/**

sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.sourceEncoding=UTF-8
